


export const mockModels = [
 /*{
  id: 1,
  title: 'Figura Goku',
  category: 'Fantasía',
  date: '2025-06-15',
  views: 140,
  description: 'Una figura detallada de un dragón para impresión 3D.',
  image: require('../assets/images/goku.jpg'),
  files: [
      {
        id: 1,
        name: 'dragon_model.stl',
        preview: require('../assets/images/goku.jpg'),
        downloadUrl: 'https://ejemplo.com/dragon_model.stl',
      }
    ]
  },

  
    
  {
    id: '2',
    image: require('../assets/images/gumball.jpg'),
    title: 'Figura Gumball',
  },
  {
    id: '3',
    image: require('../assets/images/messi.jpg'),
    title: 'Figura Messi',
  },
  {
    id: '4',
    image: require('../assets/images/minipeka.jpg'),
    title: 'Mini Pekka',
  },
  {
    id: '5',
    image: require('../assets/images/perro.jpg'),
    title: 'Figura Perro Siberiano',
  },
   {
    id: '6',
    image: require('../assets/images/superheroes.jpg'),
    title: 'Llaveros SuperHeroes',
  },*/
  {
    id: 20,
    title: 'Espada Medieval',
    category: 'Fantasía',
    tags: ['fantasía', 'arma', 'histórico'],
    owner: { username: 'forjadorX' },
    image: require('../assets/images/espada.jpg'),
    downloads: 120,
    likes: 80,
    views: 240,
    date: '2025-06-01',
    description: 'Una espada de doble filo ideal para cosplay.',
    files: [
      {
        id: 1,
        name: 'espada.stl',
        preview: require('../assets/images/espada.jpg'),
        downloadUrl: 'https://ejemplo.com/espada.stl',
      },
    ],
  },
  {
    id: 21,
    title: 'Maceta Geométrica',
    category: 'Decoración',
    tags: ['hogar', 'plantas', 'minimalista'],
    owner: { username: 'ecoPrints' },
    image: require('../assets/images/maceta.png'),
    downloads: 342,
    likes: 134,
    views: 500,
    date: '2025-05-29',
    description: 'Ideal para suculentas o decoración moderna.',
    files: [
      {
        id: 1,
        name: 'maceta.stl',
        preview: require('../assets/images/maceta.png'),
        downloadUrl: 'https://ejemplo.com/maceta.stl',
      },
    ],
  },
  {
    id: 22,
    title: 'Organizador de Escritorio',
    category: 'Utilidad',
    tags: ['oficina', 'orden', 'impresora3d'],
    owner: { username: 'creaTools' },
    image: require('../assets/images/organizador.png'),
    downloads: 200,
    likes: 90,
    views: 420,
    date: '2025-06-10',
    description: 'Soporte multifunción para tu escritorio.',
    files: [
      {
        id: 1,
        name: 'organizador.stl',
        preview: require('../assets/images/organizador.png'),
        downloadUrl: 'https://ejemplo.com/organizador.stl',
      },
    ],
  },
  {
    id: 23,
    title: 'Figura Low-Poly de Zorro',
    category: 'Decoración',
    tags: ['animal', 'lowpoly', 'moderno'],
    owner: { username: 'polyShapes' },
    image: require('../assets/images/zorro.jpg'),
    downloads: 98,
    likes: 73,
    views: 185,
    date: '2025-05-30',
    description: 'Zorro artístico en estilo low-poly.',
    files: [
      {
        id: 1,
        name: 'zorro_lowpoly.stl',
        preview: require('../assets/images/zorro.jpg'),
        downloadUrl: 'https://ejemplo.com/zorro_lowpoly.stl',
      },
    ],
  },
  {
    id: 24,
    title: 'Soporte para Celular',
    category: 'Utilidad',
    tags: ['tecnología', 'oficina', 'celular'],
    owner: { username: 'techPrints' },
    image: require('../assets/images/soporte.png'),
    downloads: 542,
    likes: 230,
    views: 900,
    date: '2025-06-12',
    description: 'Soporte universal con ángulo ajustable.',
    files: [
      {
        id: 1,
        name: 'soporte_celular.stl',
        preview: require('../assets/images/soporte.png'),
        downloadUrl: 'https://ejemplo.com/soporte_celular.stl',
      },
    ],
  },
  {
    id: 25,
    title: 'Lámpara Lunar',
    category: 'Iluminación',
    tags: ['luz', 'luna', 'hogar'],
    owner: { username: 'astroLuz' },
    image: require('../assets/images/lampara.jpg'),
    downloads: 1200,
    likes: 540,
    views: 2200,
    date: '2025-06-05',
    description: 'Lámpara esférica con textura lunar.',
    files: [
      {
        id: 1,
        name: 'lampara_luna.stl',
        preview: require('../assets/images/lampara.jpg'),
        downloadUrl: 'https://ejemplo.com/lampara_luna.stl',
      },
    ],
  },
  {
    id: 26,
    title: 'Soporte para Auriculares',
    category: 'Gadgets',
    tags: ['gaming', 'auriculares', 'setup'],
    owner: { username: 'gamerStudio' },
    image: require('../assets/images/soporte auris.jpg'),
    downloads: 300,
    likes: 210,
    views: 480,
    date: '2025-06-03',
    description: 'Soporte curvo compatible con todos los modelos.',
    files: [
      {
        id: 1,
        name: 'stand_headphones.stl',
        preview: require('../assets/images/soporte auris.jpg'),
        downloadUrl: 'https://ejemplo.com/stand_headphones.stl',
      },
    ],
  },
  {
    id: 27,
    title: 'Torre Eiffel Miniatura',
    category: 'Arquitectura',
    tags: ['arquitectura', 'francia', 'turismo'],
    owner: { username: 'printWorld' },
    image: require('../assets/images/torre.jpg'),
    downloads: 430,
    likes: 250,
    views: 700,
    date: '2025-06-08',
    description: 'Modelo ornamental de la Torre Eiffel.',
    files: [
      {
        id: 1,
        name: 'eiffel_tower.stl',
        preview: require('../assets/images/torre.jpg'),
        downloadUrl: 'https://ejemplo.com/eiffel_tower.stl',
      },
    ],
  },
  {
    id: 28,
    title: 'Soporte para Nintendo Switch',
    category: 'Gadgets',
    tags: ['gaming', 'switch', 'soporte'],
    owner: { username: 'console3D' },
    image: require('../assets/images/soporte nintendo.png'),
    downloads: 150,
    likes: 100,
    views: 300,
    date: '2025-06-11',
    description: 'Soporte ergonómico para consola portátil.',
    files: [
      {
        id: 1,
        name: 'switch_holder.stl',
        preview: require('../assets/images/soporte nintendo.png'),
        downloadUrl: 'https://ejemplo.com/switch_holder.stl',
      },
    ],
  },
  {
    id: 29,
    title: 'Cráneo Humano Realista',
    category: 'Educación',
    tags: ['anatomía', 'ciencia', 'realismo'],
    owner: { username: 'bioMaker' },
    image: require('../assets/images/craneo.png'),
    downloads: 780,
    likes: 310,
    views: 1300,
    date: '2025-06-09',
    description: 'Modelo anatómico ideal para estudiantes.',
    files: [
      {
        id: 1,
        name: 'cranio_realista.stl',
        preview: require('../assets/images/craneo.png'),
        downloadUrl: 'https://ejemplo.com/cranio_realista.stl',
      },
    ],
  },
  {
    id: 101,
    title: 'Figura Pikachu 3D',
    category: 'Dibujos Animados',
    tags: ['pokemon', 'figura', '3d-print'],
    owner: null,
    image: require('../assets/images/pikachu.jpg'),
    downloads: 520,
    likes: 150,
    views: 1200,
    date: '2025-06-01',
    description: 'Figura de Pikachu para impresión 3D con detalles suaves.',
    files: [
      {
        id: 1,
        name: 'pikachu.stl',
        preview: require('../assets/images/pikachu.jpg'),
        downloadUrl: 'https://example.com/files/pikachu.stl',
      },
    ],
  },
  {
    id: 102,
    title: 'Cabeza de Bart Simpson',
    category: 'Dibujos Animados',
    tags: ['simpsons', 'bart', '3d-print'],
    owner: null,
    image: require('../assets/images/bart.png'),
    downloads: 330,
    likes: 95,
    views: 890,
    date: '2025-06-02',
    description: 'Modelo 3D de la cabeza de Bart Simpson para impresión detallada.',
    files: [
      {
        id: 2,
        name: 'bart_head.stl',
        preview: require('../assets/images/bart.png'),
        downloadUrl: 'https://example.com/files/bart_head.stl',
      },
    ],
  },
  {
    id: 103,
    title: 'R2-D2 Miniatura',
    category: 'Dibujos Animados',
    tags: ['star wars', 'r2d2', 'robot', '3d-print'],
    owner: null,
    image: require('../assets/images/r2d2.png'),
    downloads: 460,
    likes: 130,
    views: 1100,
    date: '2025-06-03',
    description: 'Miniatura de R2-D2 para impresión 3D con piezas móviles.',
    files: [
      {
        id: 3,
        name: 'r2d2.stl',
        preview: require('../assets/images/r2d2.png'),
        downloadUrl: 'https://example.com/files/r2d2.stl',
      },
    ],
  },
  {
    id: 104,
    title: 'Cabeza de Bob Esponja',
    category: 'Dibujos Animados',
    tags: ['bob esponja', 'figura', '3d-print'],
    owner: null,
    image: require('../assets/images/bob.png'),
    downloads: 375,
    likes: 110,
    views: 950,
    date: '2025-06-04',
    description: 'Cabeza de Bob Esponja para impresión 3D con colores definidos.',
    files: [
      {
        id: 4,
        name: 'bob_head.stl',
        preview: require('../assets/images/bob.png'),
        downloadUrl: 'https://example.com/files/bob_head.stl',
      },
    ],
  },
  {
    id: 105,
    title: 'Pieza Engranaje Mecánico',
    category: 'Piezas',
    tags: ['engranaje', 'mecánico', '3d-print'],
    owner: null,
    image: require('../assets/images/engranaje.png'),
    downloads: 280,
    likes: 75,
    views: 800,
    date: '2025-06-05',
    description: 'Engranaje funcional para impresoras 3D y proyectos mecánicos.',
    files: [
      {
        id: 5,
        name: 'gear.stl',
        preview: require('../assets/images/engranaje.png'),
        downloadUrl: 'https://example.com/files/gear.stl',
      },
    ],
  },
  {
    id: 106,
    title: 'Figura de Homer Simpson',
    category: 'Dibujos Animados',
    tags: ['simpsons', 'homer', '3d-print'],
    owner: null,
    image: require('../assets/images/homero.jpg'),
    downloads: 400,
    likes: 105,
    views: 1000,
    date: '2025-06-06',
    description: 'Figura de Homer Simpson lista para impresión 3D con base estable.',
    files: [
      {
        id: 6,
        name: 'homer.stl',
        preview: require('../assets/images/homero.jpg'),
        downloadUrl: 'https://example.com/files/homer.stl',
      },
    ],
  },
  {
    id: 107,
    title: 'Mini Mario Bros',
    category: 'Dibujos Animados',
    tags: ['mario', 'figura', '3d-print'],
    owner: null,
    image: require('../assets/images/mario.png'),
    downloads: 450,
    likes: 120,
    views: 1050,
    date: '2025-06-07',
    description: 'Mini figura de Mario Bros para impresión 3D con detalles finos.',
    files: [
      {
        id: 7,
        name: 'mario.stl',
        preview: require('../assets/images/mario.png'),
        downloadUrl: 'https://example.com/files/mario.stl',
      },
    ],
  },
  {
    id: 108,
    title: 'Pieza Tornillo Personalizado',
    category: 'Piezas',
    tags: ['tornillo', 'personalizado', '3d-print'],
    owner: null,
    image: require('../assets/images/tornillo.png'),
    downloads: 250,
    likes: 60,
    views: 700,
    date: '2025-06-08',
    description: 'Tornillo personalizado para proyectos específicos de impresión 3D.',
    files: [
      {
        id: 8,
        name: 'screw.stl',
        preview: require('../assets/images/tornillo.png'),
        downloadUrl: 'https://example.com/files/screw.stl',
      },
    ],
  },
  {
    id: 109,
    title: 'Cabeza de Mickey Mouse',
    category: 'Dibujos Animados',
    tags: ['mickey', 'disney', '3d-print'],
    owner: null,
    image: require('../assets/images/mikey.jpg'),
    downloads: 390,
    likes: 115,
    views: 980,
    date: '2025-06-09',
    description: 'Cabeza de Mickey Mouse para impresión 3D con acabado liso.',
    files: [
      {
        id: 9,
        name: 'mickey.stl',
        preview: require('../assets/images/mikey.jpg'),
        downloadUrl: 'https://example.com/files/mickey.stl',
      },
    ],
  },
  {
    id: 110,
    title: 'Pieza Engranaje Pequeño',
    category: 'Piezas',
    tags: ['engranaje', 'pequeño', '3d-print'],
    owner: null,
    image: require('../assets/images/engranaje.png'),
    downloads: 220,
    likes: 55,
    views: 600,
    date: '2025-06-10',
    description: 'Engranaje pequeño para piezas mecánicas y juguetes.',
    files: [
      {
        id: 10,
        name: 'small_gear.stl',
        preview: require('../assets/images/engranaje.png'),
        downloadUrl: 'https://example.com/files/small_gear.stl',
      },
    ],
  },
  {
    id: 111,
    title: 'Figura Totoro',
    category: 'Dibujos Animados',
    tags: ['totoro', 'studio ghibli', '3d-print'],
    owner: null,
    image: require('../assets/images/totoro.png'),
    downloads: 480,
    likes: 140,
    views: 1100,
    date: '2025-06-11',
    description: 'Figura de Totoro para impresión 3D con detalles suaves.',
    files: [
      {
        id: 11,
        name: 'totoro.stl',
        preview: require('../assets/images/totoro.png'),
        downloadUrl: 'https://example.com/files/totoro.stl',
      },
    ],
  },
  {
    id: 112,
    title: 'Cabeza de Olaf',
    category: 'Dibujos Animados',
    tags: ['olaf', 'frozen', '3d-print'],
    owner: null,
    image: require('../assets/images/olaf.jpeg'),
    downloads: 360,
    likes: 105,
    views: 920,
    date: '2025-06-12',
    description: 'Cabeza de Olaf para impresión 3D con colores vivos.',
    files: [
      {
        id: 12,
        name: 'olaf_head.stl',
        preview: require('../assets/images/olaf.jpeg'),
        downloadUrl: 'https://example.com/files/olaf_head.stl',
      },
    ],
  },
  {
    id: 113,
    title: 'Mini Figura Sonic',
    category: 'Dibujos Animados',
    tags: ['sonic', 'figura', '3d-print'],
    owner: null,
    image: require('../assets/images/sonic.png'),
    downloads: 440,
    likes: 125,
    views: 1080,
    date: '2025-06-13',
    description: 'Mini figura de Sonic para impresión 3D con detalles definidos.',
    files: [
      {
        id: 13,
        name: 'sonic.stl',
        preview: require('../assets/images/sonic.png'),
        downloadUrl: 'https://example.com/files/sonic.stl',
      },
    ],
  },
  {
    id: 114,
    title: 'Pieza Soporte para PCB',
    category: 'Piezas',
    tags: ['soporte', 'pcb', '3d-print'],
    owner: null,
    image: require('../assets/images/pcb.jpg'),
    downloads: 270,
    likes: 70,
    views: 750,
    date: '2025-06-14',
    description: 'Soporte personalizado para placas PCB en proyectos electrónicos.',
    files: [
      {
        id: 14,
        name: 'pcb_holder.stl',
        preview: require('../assets/images/pcb.jpg'),
        downloadUrl: 'https://example.com/files/pcb_holder.stl',
      },
    ],
  },
  {
    id: 115,
    title: 'Cabeza de Goku',
    category: 'Dibujos Animados',
    tags: ['dragon ball', 'goku', '3d-print'],
    owner: null,
    image: require('../assets/images/goku.jpg'),
    downloads: 470,
    likes: 135,
    views: 1120,
    date: '2025-06-15',
    description: 'Cabeza de Goku para impresión 3D con detalles de alta calidad.',
    files: [
      {
        id: 15,
        name: 'goku_head.stl',
        preview: require('../assets/images/goku.jpg'),
        downloadUrl: 'https://example.com/files/goku_head.stl',
      },
    ],
  },
  {
    id: 116,
    title: 'Figura de Stitch',
    category: 'Dibujos Animados',
    tags: ['lilo & stitch', 'figura', '3d-print'],
    owner: null,
    image: require('../assets/images/stich.png'),
    downloads: 410,
    likes: 115,
    views: 990,
    date: '2025-06-16',
    description: 'Figura de Stitch para impresión 3D con acabado detallado.',
    files: [
      {
        id: 16,
        name: 'stitch.stl',
        preview: require('../assets/images/stich.png'),
        downloadUrl: 'https://example.com/files/stitch.stl',
      },
    ],
  },
  {
    id: 117,
    title: 'Miniatura Buzz Lightyear',
    category: 'Dibujos Animados',
    tags: ['toy story', 'buzz lightyear', '3d-print'],
    owner: null,
    image: require('../assets/images/buzz.png'),
    downloads: 430,
    likes: 120,
    views: 1020,
    date: '2025-06-17',
    description: 'Miniatura de Buzz Lightyear para impresión 3D con pose dinámica.',
    files: [
      {
        id: 17,
        name: 'buzz_lightyear.stl',
        preview: require('../assets/images/buzz.png'),
        downloadUrl: 'https://example.com/files/buzz_lightyear.stl',
      },
    ],
  },
  {
    id: 118,
    title: 'Soporte para teléfono móvil',
    category: 'Piezas',
    tags: ['soporte', 'teléfono', '3d-print'],
    owner: null,
    image: require('../assets/images/soporte.png'),
    downloads: 300,
    likes: 85,
    views: 820,
    date: '2025-06-18',
    description: 'Soporte práctico para teléfono móvil diseñado para impresión 3D.',
    files: [
      {
        id: 18,
        name: 'phone_stand.stl',
        preview: require('../assets/images/soporte.png'),
        downloadUrl: 'https://example.com/files/phone_stand.stl',
      },
    ],
  },
  {
    id: 119,
    title: 'Cabeza de Domo Kun',
    category: 'Dibujos Animados',
    tags: ['domo kun', 'figura', '3d-print'],
    owner: null,
    image: require('../assets/images/domo.png'),
    downloads: 350,
    likes: 95,
    views: 900,
    date: '2025-06-19',
    description: 'Cabeza de Domo Kun para impresión 3D con expresión característica.',
    files: [
      {
        id: 19,
        name: 'domo_kun.stl',
        preview: require('../assets/images/domo.png'),
        downloadUrl: 'https://example.com/files/domo_kun.stl',
      },
    ],
  },
  {
    id: 120,
    title: 'Mini Figura Finn',
    category: 'Dibujos Animados',
    tags: ['adventure time', 'finn', '3d-print'],
    owner: null,
    image: require('../assets/images/finn.png'),
    downloads: 420,
    likes: 115,
    views: 1010,
    date: '2025-06-20',
    description: 'Mini figura de Finn para impresión 3D con pose aventurera.',
    files: [
      {
        id: 20,
        name: 'finn.stl',
        preview: require('../assets/images/finn.png'),
        downloadUrl: 'https://example.com/files/finn.stl',
      },
    ],
  },
];
