export const mockModels = [
 /*{
  id: 1,
  title: 'Figura Goku',
  category: 'Fantasía',
  date: '2025-06-15',
  views: 140,
  description: 'Una figura detallada de un dragón para impresión 3D.',
  image: require('../assets/images/goku.jpg'),
  files: [
      {
        id: 1,
        name: 'dragon_model.stl',
        preview: require('../assets/images/goku.jpg'),
        downloadUrl: 'https://ejemplo.com/dragon_model.stl',
      }
    ]
  },

  
    
  {
    id: '2',
    image: require('../assets/images/gumball.jpg'),
    title: 'Figura Gumball',
  },
  {
    id: '3',
    image: require('../assets/images/messi.jpg'),
    title: 'Figura Messi',
  },
  {
    id: '4',
    image: require('../assets/images/minipeka.jpg'),
    title: 'Mini Pekka',
  },
  {
    id: '5',
    image: require('../assets/images/perro.jpg'),
    title: 'Figura Perro Siberiano',
  },
   {
    id: '6',
    image: require('../assets/images/superheroes.jpg'),
    title: 'Llaveros SuperHeroes',
  },*/
  {
    id: 20,
    title: 'Espada Medieval',
    category: 'Fantasía',
    tags: ['fantasía', 'arma', 'histórico'],
    owner: { username: 'forjadorX' },
    image: { uri: 'https://images.unsplash.com/photo-1608889179276-5f4be10d3a83' },
    downloads: 120,
    likes: 80,
    views: 240,
    date: '2025-06-01',
    description: 'Una espada de doble filo ideal para cosplay.',
    files: [
      {
        id: 1,
        name: 'espada.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1608889179276-5f4be10d3a83' },
        downloadUrl: 'https://ejemplo.com/espada.stl',
      },
    ],
  },
  {
    id: 21,
    title: 'Maceta Geométrica',
    category: 'Decoración',
    tags: ['hogar', 'plantas', 'minimalista'],
    owner: { username: 'ecoPrints' },
    image: { uri: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f' },
    downloads: 342,
    likes: 134,
    views: 500,
    date: '2025-05-29',
    description: 'Ideal para suculentas o decoración moderna.',
    files: [
      {
        id: 1,
        name: 'maceta.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f' },
        downloadUrl: 'https://ejemplo.com/maceta.stl',
      },
    ],
  },
  {
    id: 22,
    title: 'Organizador de Escritorio',
    category: 'Utilidad',
    tags: ['oficina', 'orden', 'impresora3d'],
    owner: { username: 'creaTools' },
    image: { uri: 'https://images.unsplash.com/photo-1583337130417-3346a1c1639b' },
    downloads: 200,
    likes: 90,
    views: 420,
    date: '2025-06-10',
    description: 'Soporte multifunción para tu escritorio.',
    files: [
      {
        id: 1,
        name: 'organizador.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1583337130417-3346a1c1639b' },
        downloadUrl: 'https://ejemplo.com/organizador.stl',
      },
    ],
  },
  {
    id: 23,
    title: 'Figura Low-Poly de Zorro',
    category: 'Decoración',
    tags: ['animal', 'lowpoly', 'moderno'],
    owner: { username: 'polyShapes' },
    image: { uri: 'https://images.unsplash.com/photo-1560807707-8cc77767d783' },
    downloads: 98,
    likes: 73,
    views: 185,
    date: '2025-05-30',
    description: 'Zorro artístico en estilo low-poly.',
    files: [
      {
        id: 1,
        name: 'zorro_lowpoly.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1560807707-8cc77767d783' },
        downloadUrl: 'https://ejemplo.com/zorro_lowpoly.stl',
      },
    ],
  },
  {
    id: 24,
    title: 'Soporte para Celular',
    category: 'Utilidad',
    tags: ['tecnología', 'oficina', 'celular'],
    owner: { username: 'techPrints' },
    image: { uri: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8' },
    downloads: 542,
    likes: 230,
    views: 900,
    date: '2025-06-12',
    description: 'Soporte universal con ángulo ajustable.',
    files: [
      {
        id: 1,
        name: 'soporte_celular.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8' },
        downloadUrl: 'https://ejemplo.com/soporte_celular.stl',
      },
    ],
  },
  {
    id: 25,
    title: 'Lámpara Lunar',
    category: 'Iluminación',
    tags: ['luz', 'luna', 'hogar'],
    owner: { username: 'astroLuz' },
    image: { uri: 'https://images.unsplash.com/photo-1511485977113-f292b5a1a3ff' },
    downloads: 1200,
    likes: 540,
    views: 2200,
    date: '2025-06-05',
    description: 'Lámpara esférica con textura lunar.',
    files: [
      {
        id: 1,
        name: 'lampara_luna.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1511485977113-f292b5a1a3ff' },
        downloadUrl: 'https://ejemplo.com/lampara_luna.stl',
      },
    ],
  },
  {
    id: 26,
    title: 'Soporte para Auriculares',
    category: 'Gadgets',
    tags: ['gaming', 'auriculares', 'setup'],
    owner: { username: 'gamerStudio' },
    image: { uri: 'https://images.unsplash.com/photo-1618005198919-e9041cc84db9' },
    downloads: 300,
    likes: 210,
    views: 480,
    date: '2025-06-03',
    description: 'Soporte curvo compatible con todos los modelos.',
    files: [
      {
        id: 1,
        name: 'stand_headphones.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1618005198919-e9041cc84db9' },
        downloadUrl: 'https://ejemplo.com/stand_headphones.stl',
      },
    ],
  },
  {
    id: 27,
    title: 'Torre Eiffel Miniatura',
    category: 'Arquitectura',
    tags: ['arquitectura', 'francia', 'turismo'],
    owner: { username: 'printWorld' },
    image: { uri: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b' },
    downloads: 430,
    likes: 250,
    views: 700,
    date: '2025-06-08',
    description: 'Modelo ornamental de la Torre Eiffel.',
    files: [
      {
        id: 1,
        name: 'eiffel_tower.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b' },
        downloadUrl: 'https://ejemplo.com/eiffel_tower.stl',
      },
    ],
  },
  {
    id: 28,
    title: 'Soporte para Nintendo Switch',
    category: 'Gadgets',
    tags: ['gaming', 'switch', 'soporte'],
    owner: { username: 'console3D' },
    image: { uri: 'https://images.unsplash.com/photo-1599785209707-28d4d03b1d0d' },
    downloads: 150,
    likes: 100,
    views: 300,
    date: '2025-06-11',
    description: 'Soporte ergonómico para consola portátil.',
    files: [
      {
        id: 1,
        name: 'switch_holder.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1599785209707-28d4d03b1d0d' },
        downloadUrl: 'https://ejemplo.com/switch_holder.stl',
      },
    ],
  },
  {
    id: 29,
    title: 'Cráneo Humano Realista',
    category: 'Educación',
    tags: ['anatomía', 'ciencia', 'realismo'],
    owner: { username: 'bioMaker' },
    image: { uri: 'https://images.unsplash.com/photo-1581090700227-2d7f7c3f7f32' },
    downloads: 780,
    likes: 310,
    views: 1300,
    date: '2025-06-09',
    description: 'Modelo anatómico ideal para estudiantes.',
    files: [
      {
        id: 1,
        name: 'cranio_realista.stl',
        preview: { uri: 'https://images.unsplash.com/photo-1581090700227-2d7f7c3f7f32' },
        downloadUrl: 'https://ejemplo.com/cranio_realista.stl',
      },
    ],
  },
];
