export const mockModelsMe = [
  {
    id: 101,
    title: 'Figura Pikachu 3D',
    category: 'Dibujos Animados',
    tags: ['pokemon', 'figura', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2017/02/20/17/58/pikachu-2083680_1280.png' },
    downloads: 520,
    likes: 150,
    views: 1200,
    date: '2025-06-01',
    description: 'Figura de Pikachu para impresión 3D con detalles suaves.',
    files: [
      {
        id: 1,
        name: 'pikachu.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2017/02/20/17/58/pikachu-2083680_1280.png' },
        downloadUrl: 'https://example.com/files/pikachu.stl',
      },
    ],
  },
  {
    id: 102,
    title: 'Cabeza de Bart Simpson',
    category: 'Dibujos Animados',
    tags: ['simpsons', 'bart', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/a/aa/Bart_Simpson_200px.png' },
    downloads: 330,
    likes: 95,
    views: 890,
    date: '2025-06-02',
    description: 'Modelo 3D de la cabeza de Bart Simpson para impresión detallada.',
    files: [
      {
        id: 2,
        name: 'bart_head.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/a/aa/Bart_Simpson_200px.png' },
        downloadUrl: 'https://example.com/files/bart_head.stl',
      },
    ],
  },
  {
    id: 103,
    title: 'R2-D2 Miniatura',
    category: 'Dibujos Animados',
    tags: ['star wars', 'r2d2', 'robot', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2015/09/10/22/42/r2d2-935244_1280.jpg' },
    downloads: 460,
    likes: 130,
    views: 1100,
    date: '2025-06-03',
    description: 'Miniatura de R2-D2 para impresión 3D con piezas móviles.',
    files: [
      {
        id: 3,
        name: 'r2d2.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2015/09/10/22/42/r2d2-935244_1280.jpg' },
        downloadUrl: 'https://example.com/files/r2d2.stl',
      },
    ],
  },
  {
    id: 104,
    title: 'Cabeza de Bob Esponja',
    category: 'Dibujos Animados',
    tags: ['bob esponja', 'figura', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/3/3b/SpongeBob_SquarePants_character.svg' },
    downloads: 375,
    likes: 110,
    views: 950,
    date: '2025-06-04',
    description: 'Cabeza de Bob Esponja para impresión 3D con colores definidos.',
    files: [
      {
        id: 4,
        name: 'bob_head.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/3/3b/SpongeBob_SquarePants_character.svg' },
        downloadUrl: 'https://example.com/files/bob_head.stl',
      },
    ],
  },
  {
    id: 105,
    title: 'Pieza Engranaje Mecánico',
    category: 'Piezas',
    tags: ['engranaje', 'mecánico', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2013/07/12/15/35/gear-150647_1280.png' },
    downloads: 280,
    likes: 75,
    views: 800,
    date: '2025-06-05',
    description: 'Engranaje funcional para impresoras 3D y proyectos mecánicos.',
    files: [
      {
        id: 5,
        name: 'gear.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2013/07/12/15/35/gear-150647_1280.png' },
        downloadUrl: 'https://example.com/files/gear.stl',
      },
    ],
  },
  {
    id: 106,
    title: 'Figura de Homer Simpson',
    category: 'Dibujos Animados',
    tags: ['simpsons', 'homer', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/0/02/Homer_Simpson_2006.png' },
    downloads: 400,
    likes: 105,
    views: 1000,
    date: '2025-06-06',
    description: 'Figura de Homer Simpson lista para impresión 3D con base estable.',
    files: [
      {
        id: 6,
        name: 'homer.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/0/02/Homer_Simpson_2006.png' },
        downloadUrl: 'https://example.com/files/homer.stl',
      },
    ],
  },
  {
    id: 107,
    title: 'Mini Mario Bros',
    category: 'Dibujos Animados',
    tags: ['mario', 'figura', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2017/05/22/09/12/mario-2335968_1280.png' },
    downloads: 450,
    likes: 120,
    views: 1050,
    date: '2025-06-07',
    description: 'Mini figura de Mario Bros para impresión 3D con detalles finos.',
    files: [
      {
        id: 7,
        name: 'mario.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2017/05/22/09/12/mario-2335968_1280.png' },
        downloadUrl: 'https://example.com/files/mario.stl',
      },
    ],
  },
  {
    id: 108,
    title: 'Pieza Tornillo Personalizado',
    category: 'Piezas',
    tags: ['tornillo', 'personalizado', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2017/08/04/10/26/screw-2574660_1280.png' },
    downloads: 250,
    likes: 60,
    views: 700,
    date: '2025-06-08',
    description: 'Tornillo personalizado para proyectos específicos de impresión 3D.',
    files: [
      {
        id: 8,
        name: 'screw.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2017/08/04/10/26/screw-2574660_1280.png' },
        downloadUrl: 'https://example.com/files/screw.stl',
      },
    ],
  },
  {
    id: 109,
    title: 'Cabeza de Mickey Mouse',
    category: 'Dibujos Animados',
    tags: ['mickey', 'disney', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Mickey_Mouse.png' },
    downloads: 390,
    likes: 115,
    views: 980,
    date: '2025-06-09',
    description: 'Cabeza de Mickey Mouse para impresión 3D con acabado liso.',
    files: [
      {
        id: 9,
        name: 'mickey.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Mickey_Mouse.png' },
        downloadUrl: 'https://example.com/files/mickey.stl',
      },
    ],
  },
  {
    id: 110,
    title: 'Pieza Engranaje Pequeño',
    category: 'Piezas',
    tags: ['engranaje', 'pequeño', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2013/07/12/15/35/gear-150647_1280.png' },
    downloads: 220,
    likes: 55,
    views: 600,
    date: '2025-06-10',
    description: 'Engranaje pequeño para piezas mecánicas y juguetes.',
    files: [
      {
        id: 10,
        name: 'small_gear.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2013/07/12/15/35/gear-150647_1280.png' },
        downloadUrl: 'https://example.com/files/small_gear.stl',
      },
    ],
  },
  {
    id: 111,
    title: 'Figura Totoro',
    category: 'Dibujos Animados',
    tags: ['totoro', 'studio ghibli', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2014/04/03/11/41/totoro-310804_1280.png' },
    downloads: 480,
    likes: 140,
    views: 1100,
    date: '2025-06-11',
    description: 'Figura de Totoro para impresión 3D con detalles suaves.',
    files: [
      {
        id: 11,
        name: 'totoro.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2014/04/03/11/41/totoro-310804_1280.png' },
        downloadUrl: 'https://example.com/files/totoro.stl',
      },
    ],
  },
  {
    id: 112,
    title: 'Cabeza de Olaf',
    category: 'Dibujos Animados',
    tags: ['olaf', 'frozen', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/6/65/Olaf_Frozen.png' },
    downloads: 360,
    likes: 105,
    views: 920,
    date: '2025-06-12',
    description: 'Cabeza de Olaf para impresión 3D con colores vivos.',
    files: [
      {
        id: 12,
        name: 'olaf_head.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/6/65/Olaf_Frozen.png' },
        downloadUrl: 'https://example.com/files/olaf_head.stl',
      },
    ],
  },
  {
    id: 113,
    title: 'Mini Figura Sonic',
    category: 'Dibujos Animados',
    tags: ['sonic', 'figura', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2018/01/30/18/35/sonic-3129369_1280.png' },
    downloads: 440,
    likes: 125,
    views: 1080,
    date: '2025-06-13',
    description: 'Mini figura de Sonic para impresión 3D con detalles definidos.',
    files: [
      {
        id: 13,
        name: 'sonic.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2018/01/30/18/35/sonic-3129369_1280.png' },
        downloadUrl: 'https://example.com/files/sonic.stl',
      },
    ],
  },
  {
    id: 114,
    title: 'Pieza Soporte para PCB',
    category: 'Piezas',
    tags: ['soporte', 'pcb', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2017/02/23/17/00/circuit-board-2091810_1280.jpg' },
    downloads: 270,
    likes: 70,
    views: 750,
    date: '2025-06-14',
    description: 'Soporte personalizado para placas PCB en proyectos electrónicos.',
    files: [
      {
        id: 14,
        name: 'pcb_holder.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2017/02/23/17/00/circuit-board-2091810_1280.jpg' },
        downloadUrl: 'https://example.com/files/pcb_holder.stl',
      },
    ],
  },
  {
    id: 115,
    title: 'Cabeza de Goku',
    category: 'Dibujos Animados',
    tags: ['dragon ball', 'goku', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2014/04/02/14/16/goku-308666_1280.png' },
    downloads: 470,
    likes: 135,
    views: 1120,
    date: '2025-06-15',
    description: 'Cabeza de Goku para impresión 3D con detalles de alta calidad.',
    files: [
      {
        id: 15,
        name: 'goku_head.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2014/04/02/14/16/goku-308666_1280.png' },
        downloadUrl: 'https://example.com/files/goku_head.stl',
      },
    ],
  },
  {
    id: 116,
    title: 'Figura de Stitch',
    category: 'Dibujos Animados',
    tags: ['lilo & stitch', 'figura', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2017/08/21/23/35/stitch-2667465_1280.png' },
    downloads: 410,
    likes: 115,
    views: 990,
    date: '2025-06-16',
    description: 'Figura de Stitch para impresión 3D con acabado detallado.',
    files: [
      {
        id: 16,
        name: 'stitch.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2017/08/21/23/35/stitch-2667465_1280.png' },
        downloadUrl: 'https://example.com/files/stitch.stl',
      },
    ],
  },
  {
    id: 117,
    title: 'Miniatura Buzz Lightyear',
    category: 'Dibujos Animados',
    tags: ['toy story', 'buzz lightyear', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2016/03/27/21/56/buzz-lightyear-1282467_1280.png' },
    downloads: 430,
    likes: 120,
    views: 1020,
    date: '2025-06-17',
    description: 'Miniatura de Buzz Lightyear para impresión 3D con pose dinámica.',
    files: [
      {
        id: 17,
        name: 'buzz_lightyear.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2016/03/27/21/56/buzz-lightyear-1282467_1280.png' },
        downloadUrl: 'https://example.com/files/buzz_lightyear.stl',
      },
    ],
  },
  {
    id: 118,
    title: 'Soporte para teléfono móvil',
    category: 'Piezas',
    tags: ['soporte', 'teléfono', '3d-print'],
    owner: null,
    image: { uri: 'https://cdn.pixabay.com/photo/2018/05/24/11/27/mobile-3427826_1280.jpg' },
    downloads: 300,
    likes: 85,
    views: 820,
    date: '2025-06-18',
    description: 'Soporte práctico para teléfono móvil diseñado para impresión 3D.',
    files: [
      {
        id: 18,
        name: 'phone_stand.stl',
        preview: { uri: 'https://cdn.pixabay.com/photo/2018/05/24/11/27/mobile-3427826_1280.jpg' },
        downloadUrl: 'https://example.com/files/phone_stand.stl',
      },
    ],
  },
  {
    id: 119,
    title: 'Cabeza de Domo Kun',
    category: 'Dibujos Animados',
    tags: ['domo kun', 'figura', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/5/5f/DomoKun.svg' },
    downloads: 350,
    likes: 95,
    views: 900,
    date: '2025-06-19',
    description: 'Cabeza de Domo Kun para impresión 3D con expresión característica.',
    files: [
      {
        id: 19,
        name: 'domo_kun.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/5/5f/DomoKun.svg' },
        downloadUrl: 'https://example.com/files/domo_kun.stl',
      },
    ],
  },
  {
    id: 120,
    title: 'Mini Figura Finn',
    category: 'Dibujos Animados',
    tags: ['adventure time', 'finn', '3d-print'],
    owner: null,
    image: { uri: 'https://upload.wikimedia.org/wikipedia/en/3/3a/Finn_the_Human.png' },
    downloads: 420,
    likes: 115,
    views: 1010,
    date: '2025-06-20',
    description: 'Mini figura de Finn para impresión 3D con pose aventurera.',
    files: [
      {
        id: 20,
        name: 'finn.stl',
        preview: { uri: 'https://upload.wikimedia.org/wikipedia/en/3/3a/Finn_the_Human.png' },
        downloadUrl: 'https://example.com/files/finn.stl',
      },
    ],
  },
];
